baseURL = "https://kusumo.co.uk"
languageCode = "en-us"
title = "Kusumo.co.uk"
theme = "aether"

[params]
brand = "Programmer's Journal"
description = "just a personal blog related to compsci"
rssinmenu = true
bgimg= "/images/tile-background-1.jpg"