baseURL = "https://kusumo.co.uk"
languageCode = "en-us"
title = "Kusumo.co.uk"
theme = "aether"
disqusShortname = "kusumo96"
googleAnalytics = "UA-112010525-2"

[params]
brand = "Programmer's Note"
description = "just a personal blog related to compsci"
rssinmenu = true
bgimg= "/images/tile-background-1.jpg"